function [handles] = update_seg_filename(hObject, eventdata, handles, fs)
handles.params.segment_filename = [handles.Segment(fs).subj '-'...
    handles.visit_number.String{1} '-' ...
    handles.Segment(fs).date '-' ...
    handles.Segment(fs).exp_type '-' ...
    handles.Segment(fs).exp_condition '-' ...
    handles.Segment(fs).stim_axis '-' ...
    handles.Segment(fs).ecomb '-' ...
    num2str(handles.Segment(fs).rate) 'pps' '-' ...
    'phase1Dur' num2str(handles.Segment(fs).p1d) '-' ...
    'phase2Dur' num2str(handles.Segment(fs).p2d) '-' ...
    'IPG' num2str(handles.Segment(fs).ipg) '-' ...
    'phase1Amp' num2str(handles.Segment(fs).p1amp) '-' ...
    'phase2Amp' num2str(handles.Segment(fs).p1amp) ...
    handles.Segment(fs).exp_defS ...
    handles.AvC.String{1}];

set(hObject,'String',handles.params.segment_filename);